spring:
  application:
    name: "http-service1"
  profiles:
    active: dev
#
#  zipkin:
#    enable: true
  sleuth:
    propagation.type: W3C
    enabled: true
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://192.168.131.129:4317
#          endpoint: http://localhost:4317
#          endpoint: http://localhost:55678
      multiple-tracer-configs-detector-enabled: false

    redis:
      enabled: true

  redis:
    host: 192.168.131.129
    port: 6379
    password: root


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
    io.opentelemetry: DEBUG